"""Renders loadtest/report.json (a list of run summaries) into loadtest/report.md.

Run:  python -m loadtest.render_report
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def main() -> None:
    runs = json.loads((HERE / "report.json").read_text())

    lines = [
        "# Load test report",
        "",
        "Generated by `python -m loadtest.render_report` from `loadtest/report.json`.",
        "Each row is one full run of `python -m loadtest.run_loadtest` against a",
        "separately-configured server instance (same MockBackend, same machine).",
        "",
        "| Label | Concurrency | Requests | Errors | Throughput (req/s) | p50 (ms) | p95 (ms) | p99 (ms) | Cache hit ratio |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in runs:
        lat = r["latency_ms"]
        lines.append(
            f"| {r['label']} | {r['concurrency']} | {r['total_requests']} | {r['errors']} | "
            f"{r['throughput_rps']} | {lat['p50']} | {lat['p95']} | {lat['p99']} | "
            f"{r['cache_hit_ratio']} |"
        )

    (HERE / "report.md").write_text("\n".join(lines) + "\n")
    print((HERE / "report.md").read_text())


if __name__ == "__main__":
    main()
